### PR TITLE
Referenced assemblies transpilation

### PR DESCRIPTION
**Pull request by nenoNaninu**
Related #37 #38

### CODE REVIEW

**Comment by nenoNaninu** [comment]
Lack of test cases for new features.

**Comment by nenoNaninu** [comment]
- [ ] add tests
- [ ] update README.md

**Comment by Vulthil** [comment]
This will probably do the trick, however, it will also transpile classes which reference the attribute from different assemblies, which you are NOT referencing in the targeted .csproj file.

**Comment by nenoNaninu** [comment]
I'm filtering on the condition of whether the attribute is annotated [here](https://github.com/nenoNaninu/Tapper/blob/referenced_assemblies_transpilation/src/Tapper/RoslynExtensions.TypeCollector.cs#L67-L79). Still, does such a problem occur?

**Comment by Vulthil** [comment]
> I'm filtering on the condition of whether the attribute is annotated [here](https://github.com/nenoNaninu/Tapper/blob/referenced_assemblies_transpilation/src/Tapper/RoslynExtensions.TypeCollector.cs#L67-L79). Still, does such a problem occur?

Yes, imagine someone has a reference to Tapper.Attributes and include the attribute, but it's totally unrelated to the transpiling you are performing.

**Comment by nenoNaninu** [comment]
OK, I understand what you are saying. That behavior is appropriate.

If "TapperAttributes" is used in another assembly (dll), that assembly is library code. Definitely.

If `TapperAttributes` is used in a library, it is designed to interact with the front end. Therefore, it is appropriate to target it for transpile.

**Comment by Vulthil** [comment]
What if it is used in an Assembly/Library which is not under the control of the programmer, but still references the Attribute because the referenced Library also has Tapper.Attributes ?

Why would those class need to be transpiled, unless explicitely referenced by the classes from the targeted .csproj?

**Comment by nenoNaninu** [comment]
>What if it is used in an Assembly/Library which is not under the control of the programmer, but still references the Attribute because the referenced Library also has Tapper.Attributes ?

If the library references `Tapper.Attributes` and has `[TranspilationSource]` annotated to the type, it will be transpile to TypeScript if you passed "-asm true"  as a command line argument.

**Comment by Vulthil** [comment]
Yes, but what if it's a Library from "XYZ Company" which is not relevant to transpile, but they also use Tapper Internally ?

**Comment by nenoNaninu** [comment]
Does the "XYZ Company" library communicate with the front end? If it communicates with the front end, then it is correct to transpile it. If the library does not provide the ability to communicate with the front end, but is using Tapper, then the "XYZ Company" library has the incorrect architecture. Tapper does not care about that problem(incorrect architecture).

Well, in most cases, tapper users will not encounter such problems if they use the default value (`-asm false`), since only code under their control will be transpiled.

**Comment by Vulthil** [comment]
What do you mean "communicate with the frontend" ?

Tapper is only for generate Typescript types. No communication.

**Comment by Vulthil** [comment]
If you merge this, you will potentially introduce unwanted Typescript types in the transpiled output.
Unwanted types that you do not intend to use, and are not referenced by any type in your compilation.

**Comment by nenoNaninu** [comment]
TypeScript types are generated in order to allow C# (backend) and TypeScript (frontend) applications to communicate with each other. So tapper generates TypeScript code suitable for serializers such as JSON/msgpack. I do not consider generating TypeScript from C# for any other use case.

**Comment by Vulthil** [comment]
All I'm saying is that unwanted types might be generated.
That is all.

**Comment by nenoNaninu** [comment]
If your use case is one that I think is valid, I will consider it. Otherwise, this PR will be merged as is. Also, I want the feature of this PR for myself.

**Comment by Vulthil** [comment]
You are free to do whatever you see fit. It is your project after all.

But consider this scenario:

Someone has a backend project, using Tapper Attributes in order to provide a TypedSignalRClient for both Typescript and C#.

I make a C# project, which uses their Typed C# client in order to communicate with them.
I also provide a SignalR hub, which does NOT depend on any types from the other project mentioned earlier.
I now want to generate Typescript types for my Typed Typescript Client using Tapper.

I will end up with the Types from the first Backend project being transpiled into my typescript types, which was not my intention.

**Comment by nenoNaninu** [comment]
Are you saying that end users will only have access to the Hub you provided?

>I also provide a SignalR hub, which does NOT depend on any types from the other project mentioned earlier.

If so, I think that `-asm false` would be sufficient if it is not dependent on an external project.

**Comment by Vulthil** [comment]
A project structure like:

SomeProject.SignalR
   - SomeProject.SignalR.Library
   
 would not work with `-asm false` in the scenario provided before.

**Comment by nenoNaninu** [comment]
I am beginning to think that adding the ability to transpile only specific namespaces is a good idea.

**Pull request merged**
