### PR TITLE
Feature/referenced types

### PR DESCRIPTION
**Pull request by Vulthil**
This will allow Tapper to generate typescript types for classes referenced by classes in the targeted .csrproj file, if they are annotated with the `TranspilationSourceAttribute`.

A few tests have been added. Both for the Typescript project and for the individual parts.

The test will all start from a clean cache of the `INamedTypeSymbol[]` in the RoslynExtensions, as different compilations are involved.
The tests will therefore individually take longer, but the overall performance of the generator should be unchanged.

The extensions to the interfaces for `ICodeGenerator` and `ITypeMapperProvider` are included as these will be needed for the implementation of the references from the SignalR client generator project.

### CODE REVIEW

**Comment by Vulthil** [comment]
The yarn.lock file change is an upgrade of jest, as the version used earlier had issues with Node 18

**Comment by nenoNaninu** [comment]
> The yarn.lock file change is an upgrade of jest, as the version used earlier had issues with Node 18

Please use node16(LTS). Don't change yarn.lock file.

**Comment by nenoNaninu** [comment]
>The extensions to the interfaces for ICodeGenerator and ITypeMapperProvider are included as these will be needed for the implementation of the references from the SignalR client generator project.

Don't let other repository code affect the repository  code.

**Comment by Vulthil** [comment]
> Don't let test code affect the main library code. `[assembly: InternalsVisibleTo("Tapper.Tests")]` is not good.

How would you go about resetting the cached types in the RoslynExtensions file?
The flow of the compilation is only supposed to handle 1 compilation at a time, meaning that the statically cached type symbols are fine, however, the tests now include a second compilation that need to be tested, and the cached type symbols are not reflecting the new compilation.

The `InternalsVisibleToAttribute` was the cleanest way I could find that did not pollute the public API of the project.

**Comment by Vulthil** [comment]
> Don't let other repository code affect the repository code.

Reverted these changes.

The implementation in the other Repository will now be a copy-paste of the code transpiling the types.

**Comment by nenoNaninu** [comment]
>How would you go about resetting the cached types in the RoslynExtensions file?

It seems that it would be better to add a new test project.
Limiting to one compilation per test project makes things easier.

**Comment by nenoNaninu** [comment]
Why is `Tapper.Analyzer.csproj` being changed?

**Comment by Vulthil** [comment]
> Why is `Tapper.Analyzer.csproj` being changed?

The Tapper.Analyzer.csproj file had to reference the ReferencedTypeCollector.cs file, other wise it would not build as the RoslynExtensions.cs file depends on it, and the file is a Link.

**Comment by Vulthil** [comment]
> It seems that it would be better to add a new test project.
> Limiting to one compilation per test project makes things easier.

It seems that the seperate test assembly did the trick. I had not thought about that.
Removed the InternalsVisibleToAttribute, and the ClearCachedMethod which was no longer used.

**Comment by nenoNaninu** [comment]
There were several points about the implementation of this PR that I was unsatisfied with, so I implemented a similar feature in #39. I need more time to merge them because I have not written the tests yet, but I will release the requested features.

Thank you for sending the pull request!

**Pull request closed without merging**
